name:                Hex
version:             0.1.0.0
github:              "RyanMcNamara86/Hex"
license:             MIT
author:              "Ryan McNamara"
maintainer:          "gn341ram@gmail.com"
copyright:           "2019 RyanMcNamara"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: A library for hexagonal tilings, intended for use in video games.

dependencies:
- base >= 4.7 && < 5
- linear
- containers

library:
  source-dirs: src

tests:
  Hex-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hex
    - hspec
    - QuickCheck
    - test-invariant
